name: shift_management_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/passwords_import.json
  fonts:
    - family: CustomRoboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

